### ISSUE TITLE
Broken EXE when building with pyinstaller

### ISSUE THREAD

**Issue by carverhaines** [CappyT/g14control#5]
@CappyT , do you know what is going wrong with the exe? Does it give any errors on compiling, or does it just not function once completed?

**Comment by carverhaines** [comment]
Can you tell me where 'pystray._win32' is required? Why is it a hidden import on compile?

It seems like because we are running it on 64 bit OS, that it is not supported.

Bug trace:

```
Traceback (most recent call last):
  File "C:\Users\${user}\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
    module.run()
  File "C:\Users\${user}\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "main.pyw", line 1, in <module>
    import pystray
  File "C:\Users\${user}\AppData\Local\Programs\Python\Python38\lib\site-packages\pystray\__init__.py", line 48, in <module>
    Icon = backend().Icon
  File "C:\Users\${user}\AppData\Local\Programs\Python\Python38\lib\site-packages\pystray\__init__.py", line 44, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: No module named 'pystray._win32'
```

**Comment by carverhaines** [comment]
Interestingly, when I uninstalled python64 and installed pythong 32 bit instead, running ` python main.pyw` gives me the same behavior as the non-functioning executable, where it will launch and appear to be running, however no notifications and changing settings does not appear to do anything (although getting  atrofac_cli] Success messages...)

**Comment by carverhaines** [comment]
#6

**Comment by CappyT** [comment]
I was proposing to use Nuitka compiler, but I guess cxFreeze will do absolutely good.
